// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnL2X_Qiz8fnUcjRIImg2M_FX06OtprjU',
    appId: '1:891033436151:android:2a1eb3c2ac3732796138f2',
    messagingSenderId: '891033436151',
    projectId: 'notif-8f094',
    storageBucket: 'notif-8f094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmYTuiK88xUXtlU06LSD5Qegn5zsfEyWM',
    appId: '1:891033436151:ios:25e196f53578d0416138f2',
    messagingSenderId: '891033436151',
    projectId: 'notif-8f094',
    storageBucket: 'notif-8f094.appspot.com',
    androidClientId: '891033436151-8ggiumhfbq03rdphtmr9p26im9snlgih.apps.googleusercontent.com',
    iosClientId: '891033436151-ml45fna73a451gls2fu6dk8u89kmv386.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationtest.notificationTest',
  );
}
